# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bun"
    # Look for `package.json` and `bun.lock` files in the frontend directory
    directory: "/frontend/"
    # Check the Bun registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    # Look for `go.mod` and `go.sum` files in the backend directory
    directory: "/backend/"
    # Check the Go modules registry for updates monthly
    schedule:
      interval: "monthly"
